import { Category, MenuItem, Restaurant } from "@/types";

export const DEMO_OWNER_ID = "00000000-0000-0000-0000-000000000001";
export const DEMO_RESTAURANT_ID = "11111111-1111-1111-1111-111111111111";

export const DEMO_RESTAURANT: Restaurant = {
  id: DEMO_RESTAURANT_ID,
  owner_id: DEMO_OWNER_ID,
  name: "Cafe Aroma",
  slug: "cafe-aroma",
  description: "Artisanal coffee, handcrafted teas, and freshly toasted treats in an ambient setting.",
  restaurant_type: "Café",
  dietary_type: "both",
  logo_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=200&auto=format&fit=crop&q=80",
  cover_image_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80",
  phone: "+91 98765 43210",
  whatsapp: "+919876543210",
  instagram: "cafearoma.official",
  address: "Shop 14, Ground Floor, Indiranagar 100ft Road",
  city: "Bengaluru",
  state: "Karnataka",
  country: "India",
  currency: "INR",
  template_key: "cafe",
  primary_color: "#10B981",
  secondary_color: "#047857",
  published: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-hot-bev",
    restaurant_id: DEMO_RESTAURANT_ID,
    name: "Hot Beverages",
    description: "Freshly brewed teas and espresso classics",
    position: 0,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-cold-bev",
    restaurant_id: DEMO_RESTAURANT_ID,
    name: "Cold Beverages",
    description: "Chilled refreshers, cold brews, and shakes",
    position: 1,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-snacks",
    restaurant_id: DEMO_RESTAURANT_ID,
    name: "Snacks",
    description: "Crispy grilled sandwiches and quick munchies",
    position: 2,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-desserts",
    restaurant_id: DEMO_RESTAURANT_ID,
    name: "Desserts",
    description: "Decadent sweet endings baked fresh daily",
    position: 3,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_ITEMS: MenuItem[] = [
  // Hot Beverages
  {
    id: "item-masala-chai",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-hot-bev",
    name: "Masala Chai",
    description: "Traditional Indian spiced milk tea infused with crushed cardamom, ginger, and aromatic cloves.",
    price: 30,
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: true,
    is_spicy: false,
    is_vegan: false,
    is_jain: true,
    position: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-ginger-chai",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-hot-bev",
    name: "Ginger Chai",
    description: "Strong milk tea brewed with freshly grated spicy ginger root.",
    price: 35,
    image_url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: true,
    is_vegan: false,
    is_jain: true,
    position: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-cappuccino",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-hot-bev",
    name: "Cappuccino",
    description: "Rich dark espresso topped with velvety steamed milk foam and cocoa dusting.",
    price: 120,
    image_url: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: false,
    is_jain: true,
    position: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-cafe-latte",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-hot-bev",
    name: "Café Latte",
    description: "Smooth double espresso poured gently with silky steamed whole milk.",
    price: 130,
    image_url: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: false,
    is_jain: true,
    position: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Cold Beverages
  {
    id: "item-cold-coffee",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-cold-bev",
    name: "Cold Coffee",
    description: "Thick creamy blended cold coffee served with chocolate syrup drizzle.",
    price: 150,
    image_url: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: true,
    is_spicy: false,
    is_vegan: false,
    is_jain: true,
    position: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-iced-americano",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-cold-bev",
    name: "Iced Americano",
    description: "Bold espresso shots poured over crystal clear ice and chilled water.",
    price: 110,
    image_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: true,
    is_jain: true,
    position: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-mango-shake",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-cold-bev",
    name: "Mango Shake",
    description: "Real Alphonso mango pulp blended with rich vanilla cream and crushed ice.",
    price: 140,
    image_url: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: false,
    is_jain: false,
    position: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Snacks
  {
    id: "item-veg-grilled-sandwich",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-snacks",
    name: "Veg Grilled Sandwich",
    description: "Fresh cucumbers, ripe tomatoes, bell peppers, mint coriander chutney and melted cheese.",
    price: 120,
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: false,
    is_jain: true,
    position: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-paneer-tikka-sandwich",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-snacks",
    name: "Paneer Tikka Sandwich",
    description: "Spiced chargrilled paneer cubes, roasted bell peppers, and smoky tandoori spread.",
    price: 160,
    image_url: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: true,
    is_spicy: true,
    is_vegan: false,
    is_jain: false,
    position: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-french-fries",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-snacks",
    name: "French Fries",
    description: "Golden crispy salted potato fries served with spiced peri-peri dip.",
    price: 100,
    image_url: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop&q=80",
    food_type: "veg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: true,
    is_jain: true,
    position: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Desserts
  {
    id: "item-chocolate-brownie",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-desserts",
    name: "Chocolate Brownie",
    description: "Warm gooey Belgian chocolate fudge brownie loaded with molten chocolate chunks.",
    price: 150,
    image_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80",
    food_type: "egg",
    is_available: true,
    is_visible: true,
    is_bestseller: false,
    is_spicy: false,
    is_vegan: false,
    is_jain: false,
    position: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-cheesecake",
    restaurant_id: DEMO_RESTAURANT_ID,
    category_id: "cat-desserts",
    name: "Cheesecake",
    description: "Classic New York baked cheesecake layered on buttery graham cracker crust.",
    price: 180,
    image_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&auto=format&fit=crop&q=80",
    food_type: "egg",
    is_available: true,
    is_visible: true,
    is_bestseller: true,
    is_spicy: false,
    is_vegan: false,
    is_jain: false,
    position: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
